#!/bin/zsh

branch=$(git branch |egrep -o 'master|main')

echo $branch
# which git && git remote -v && which git
git fetch origin $branch && git rebase origin/$branch && git push --set-upstream origin $( git rev-parse --abbrev-ref HEAD) -f && glab mr create --no-editor -f -y
